// AUTHORISATION ACTIONS
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

// NEW GAME FORM ACTIONS
export const PICK_NAME_SUCCESS = 'PICK_NAME_SUCCESS';
export const PICK_NAME_FAIL = 'PICK_NAME_FAIL';
export const PICK_PLAYER_NUMBER_SUCCESS = 'PICK_PLAYER_NUMBER_SUCCESS';
export const PICK_PLAYER_NUMBER_FAIL = 'PICK_PLAYER_NUMBER_FAIL';
export const PICK_FIELD_SUCCESS = 'PICK_FIELD_SUCCESS';
export const PICK_FIELD_FAIL = 'PICK_FIELD_FAIL';
export const PICK_DATE_SUCCESS = 'PICK_DATE_SUCCESS';
export const PICK_DATE_FAIL = 'PICK_DATE_FAIL';
export const NEW_GAME_FORM_SUBIMT_SUCCESS = 'NEW_GAME_FORM_SUBIMT_SUCCESS';
export const NEW_GAME_FORM_FAIL = 'NEW_GAME_FORM_FAIL';

// GAMES API ACTIONS
export const SAVE_GAME = 'SAVE_GAME';
export const LIST_USERS_GAMES = 'LIST_USERS_GAMES';
export const FETCHING_USERS_GAMES = 'FETCHING_USERS_GAMES';
export const LIST_NEAR_GAMES = 'LIST_NEAR_GAMES';
export const FETCHING_NEAR_GAMES = 'FETCHING_NEAR_GAMES';
export const LIST_FIELDS = 'LIST_NEAR_FIELDS';

// GAME STATE ACTIONS
export const SHOW_GAME_INFO = 'SHOW_GAME_INFO';
