// AUTHORISATION ACTIONS
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SIGN_OUT = 'SIGN_OUT';

// NEW GAME FORM ACTIONS
export const PICK_NAME_SUCCESS = 'PICK_NAME_SUCCESS';
export const PICK_NAME_FAIL = 'PICK_NAME_FAIL';
export const PICK_PLAYER_NUMBER_SUCCESS = 'PICK_PLAYER_NUMBER_SUCCESS';
export const PICK_PLAYER_NUMBER_FAIL = 'PICK_PLAYER_NUMBER_FAIL';
export const PICK_FIELD_SUCCESS = 'PICK_FIELD_SUCCESS';
export const PICK_FIELD_FAIL = 'PICK_FIELD_FAIL';
export const PICK_DATE_SUCCESS = 'PICK_DATE_SUCCESS';
export const PICK_DATE_FAIL = 'PICK_DATE_FAIL';
export const NEW_GAME_FORM_SUBIMT_SUCCESS = 'NEW_GAME_FORM_SUBIMT_SUCCESS';
export const NEW_GAME_FORM_FAIL = 'NEW_GAME_FORM_FAIL';

// GAMES API ACTIONS
export const SAVE_GAME = 'SAVE_GAME';
export const LIST_GAMES = 'LIST_GAMES';
export const FETCHING_USERS_GAMES = 'FETCHING_USERS_GAMES';
export const LIST_NEAR_GAMES = 'LIST_NEAR_GAMES';
export const FETCHING_NEAR_GAMES = 'FETCHING_NEAR_GAMES';
export const LIST_FIELDS = 'LIST_NEAR_FIELDS';
export const LIST_NEAR_GAMES_FAIL = 'LIST_NEAR_GAMES_FAIL';
export const LIST_USERS_GAMES_FAIL = 'LIST_GAMES_FAIL';
export const REMOVING_GAME = 'REMOVING_GAME';
export const REMOVE_GAME_SUCCESS = 'REMOVE_GAME_SUCCESS';
export const REMOVE_GAME_FAIL = 'REMOVE_GAME_FAIL';

// GAME STATE ACTIONS
export const SHOW_GAME_INFO = 'SHOW_GAME_INFO';
export const USER_DETAILS = 'USER_DETAILS';
export const OTHER_USER_DETAILS = 'OTHER_USER_DETAILS';
export const FETCHING_USER_DETAILS = 'FETCHING_USER_DETAILS';
export const FETCHING_USER_DETAILS_FAILED = 'FETCHING_USER_DETAILS_FAILED';
export const UPDATING_USER_DETAILS = 'UPDATING_USER_DETAILS';
export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS';
export const UPDATE_USER_DETAIL_FAIL = 'UPDATE_USER_DETAIL_FAIL';
export const LOCATION = 'LOCATION';

// GAME MANAGER ACTIONS
export const JOINING_GAME = 'JOINING_GAME';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAIL = 'JOIN_GAME_FAIL';
export const REMOVING_PLAYER = 'REMOVING_PLAYER';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const REMOVE_PLAYER_FAIL = 'REMOVE_PLAYER_FAIL';
