export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const PICK_NAME_SUCCESS = 'PICK_NAME_SUCCESS';
export const PICK_NAME_FAIL = 'PICK_NAME_FAIL';
export const PICK_PLAYER_NUMBER_SUCCESS = 'PICK_PLAYER_NUMBER_SUCCESS';
export const PICK_PLAYER_NUMBER_FAIL = 'PICK_PLAYER_NUMBER_FAIL';
export const PICK_FIELD_SUCCESS = 'PICK_FIELD_SUCCESS';
export const PICK_FIELD_FAIL = 'PICK_FIELD_FAIL';
export const PICK_DATE_SUCCESS = 'PICK_DATE_SUCCESS';
export const PICK_DATE_FAIL = 'PICK_DATE_FAIL';
